spring:
    kafka:
        consumer:
            auto-offset-reset: earliest
            bootstrap-servers: 172.21.6.223:9092
            group-id: group-id
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: 172.21.6.223:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer